name: Release

on: [push, workflow_dispatch]

jobs:
    release:
        if: startsWith(github.ref, 'refs/tags/v')
        runs-on: ubuntu-latest
        timeout-minutes: 25
        steps:
            - name: Checkout
              uses: actions/checkout@v3
              with:
                fetch-depth: 0

            - uses: actions/setup-node@v1
              with:
                node-version: 12
                registry-url: https://registry.npmjs.org/

            - name: Install deps
              run: npm install

            - name: Build package
              run: npm build

            - name: Get tag
              uses: martinbeentjes/npm-get-version-action@master
              id: get_tag

            - name: Get Changelog Entry
              id: get_changelog
              uses: mindsers/changelog-reader-action@v2
              with:
                validation_depth: 10
                version: ${{ steps.get_tag.outputs.current-version }}

            - name: Create Release
              uses: ncipollo/release-action@v1
              with:
                body: ${{ steps.get_changelog.outputs.changes }}
                tag: ${{ steps.get_changelog.outputs.version }}
                token: ${{ secrets.GITHUB_TOKEN }}

            - name: Publish to NPM
              run: npm publish
              env:
                NODE_AUTH_TOKEN: ${{secrets.npm_token}}
